name: run test.py

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - feature-*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout repo
      uses: actions/checkout@v2
    - name: use python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: install requirements
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: run test
      run: pytest test.py
